### ISSUE TITLE
Issues I faced while installing the requirements.txt

### ISSUE THREAD

**Issue by ghost** [muthuruban/SophiaProject#1]
![requirements txt - Git - Visual Studio Code 22-Jan-24 1_09_41 PM (2)](https://github.com/muthuruban/SophiaProject/assets/157316684/a3949261-19d3-4be5-b036-fa1e3cf5374f)

Change some module names in requirements.txt :-

1) sklearn -->scikit-learn 
2) speech_recognition --> SpeechRecognition

![requirements txt - Git - Visual Studio Code 22-Jan-24 2_07_52 PM_LI](https://github.com/muthuruban/SophiaProject/assets/157316684/374e4cfc-df97-4bee-b206-9e6d1065cf40)

> **keras and tensorflow** install aagamatuthu ra..😅
> 
> **keras a thaniya install panna try panna** athu oru 10 pakkathukku error kamikithu
> 
> **ERROR: Could not build wheels for dm-tree, which is required to install pyproject.toml-based projects**
>  **nu varuthu** 
> 
> **I'LL INCLUDE THAT ERROR HERE :-**
> 

E:\Internshala Training\Git\**SophiaProject>pip install keras**
Defaulting to user installation because normal site-packages is not writeable
Collecting keras
  Using cached keras-3.0.4-py3-none-any.whl.metadata (4.8 kB)
Collecting absl-py (from keras)
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: numpy in c:\users\hp\appdata\roaming\python\python312\site-packages (from keras) (1.26.3)
Collecting rich (from keras)
  Downloading rich-13.7.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras)
  Downloading namex-0.0.7-py3-none-any.whl (5.8 kB)
Collecting h5py (from keras)
  Downloading h5py-3.10.0-cp312-cp312-win_amd64.whl.metadata (2.5 kB)
Collecting dm-tree (from keras)
  Downloading dm-tree-0.1.8.tar.gz (35 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting markdown-it-py>=2.2.0 (from rich->keras)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->keras)
  Downloading pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras)
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading keras-3.0.4-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 3.1 MB/s eta 0:00:00
Downloading absl_py-2.1.0-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 1.6 MB/s eta 0:00:00
Downloading h5py-3.10.0-cp312-cp312-win_amd64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 5.1 MB/s eta 0:00:00
Downloading rich-13.7.0-py3-none-any.whl (240 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.6/240.6 kB 2.5 MB/s eta 0:00:00
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 5.2 MB/s eta 0:00:00
Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.9 MB/s eta 0:00:00
Building wheels for collected packages: dm-tree
  Building wheel for dm-tree (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dm-tree (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\tree
      copying tree\sequence.py -> build\lib.win-amd64-cpython-312\tree
      copying tree\tree_benchmark.py -> build\lib.win-amd64-cpython-312\tree
      copying tree\tree_test.py -> build\lib.win-amd64-cpython-312\tree
      copying tree\__init__.py -> build\lib.win-amd64-cpython-312\tree
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 77, in _check_build_environment
        File "C:\Program Files\Python312\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main 
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel   
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup     
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup     
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup    
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in 
run
          self.run_command(cmd_name)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-oye314e9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 70, in run
        File "<string>", line 80, in _check_build_environment
      RuntimeError: CMake must be installed to build the following extensions: _tree
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dm-tree
Failed to build dm-tree
ERROR: Could not build wheels for dm-tree, which is required to install pyproject.toml-based projects

> **AND FINALLY TENSORFLOW 🌝**

![requirements txt - Git - Visual Studio Code 22-Jan-24 2_26_06 PM_LI](https://github.com/muthuruban/SophiaProject/assets/157316684/2f9ba7f2-9bab-4f99-963c-695bb7002248)

I AM USING PYTHON 3.12.1 Google search panni pathathula TensorFlow is tested and supported on the following nu

1. python 3.8 - 3.11

nu vanthuthu so athanala support aagala ya nu therla 🤷‍♂️

![Install TensorFlow 2 - Google Chrome 22-Jan-24 2_30_43 PM](https://github.com/muthuruban/SophiaProject/assets/157316684/4ea28649-3b50-426f-86e8-ff8c682d6e82)

**Comment by muthuruban** [comment]
@J-Melvin For that you need to install Visual Studio latest with C++ Development package to make it install on your system. Try this

**Comment by ghost** [comment]
Ya kitta irruku da

![2024-01-23 11 19 36 444  Gemoo Snap (2)](https://github.com/muthuruban/SophiaProject/assets/157316684/70a23f48-869a-4801-8752-ef11f46001f4)

![Visual Studio Installer 23-Jan-24 10_17_34 AM](https://github.com/muthuruban/SophiaProject/assets/157316684/7149e87c-13cd-44f8-b68a-18af941a5b31)

**Can you giude me..!**

**Comment by muthuruban** [comment]
click on Modify > select Desktop development with C++ > Click on Install

**Comment by ghost** [comment]
@muthuruban  **Adeii😂Already irruku da , but na thirumbavu Repair kuduthu try panni paatha but still same error..!🤷‍♂️**
